// テスト用に例外を投げる その2
throw new Error('test-error2');
